export default {
  mySidebar: [
    'intro',
    {
      type: 'category',
      label: 'v2 API',
      items: [
        'v2_api',
        {
          type: 'autogenerated',
          dirName: 'v2 API', // Generate sidebar slice from docs/v2-API
        },
      ],
    },
    {
      type: 'category',
      label: 'v1 API',
      items: [
        'v1_api',
      ],
    },
  ],
};
