name: Test the state of the build

on: [push]

jobs:
  test:
    name: Run the docusaurus test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        run: npm i
      - name: Test the build
        run: npm test
  build:
    name: Check the site builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        run: npm i
      - name: Test the build
        run: npm run build
